language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO=Django==1.8
  - DJANGO=Django==1.9
  - DJANGO=Django==1.10
  - DJANGO=Django==1.11.3

install:
  - pip install $DJANGO
script:
  - python setup.py test
notifications:
  email:
    recipients:
      - baguage@gmail.com
    on_success: always
    on_failure: always