language: python
env:
  global:
    - SECRET_KEY=travis
matrix:
    python:
      - "2.7"
      - "3.4"
      - "3.5"
    env:
      - DJANGO=django-1.8
      - DJANGO=django-1.9
      - DJANGO=django-1.10

install:
  - pip install $DJANGO
script:
  - python setup.py test
notifications:
  email:
    recipients:
      - baguage@nd.edu
    on_success: always
    on_failure: always