language: python
env:
  global:
    - SECRET_KEY=travis
matrix:
  include:
    - os:
      - linux
    - python:
      - "3.5"
      - "2.7"
    - env:
      - DJANGO=django-1.10
      - DJANGO=django-1.9
      - DJANGO=django-1.8

install:
  - echo $DJANGO; pip install $DJANGO
script:
  - python setup.py test
notifications:
  email:
    recipients:
      - baguage@nd.edu
    on_success: always
    on_failure: always