language: python
env:
  global:
    - SECRET_KEY=travis
matrix:
  include:
    - os: linux
      python: "3.5"
      env: PYTHON=/usr/bin/python3.5
    - os: linux
      python: "2.7"
      env: PYTHON=/usr/bin/python2.7

install:
  - pip install django
script:
  - python setup.py test
notifications:
  email:
    recipients:
      - baguage@nd.edu
    on_success: always
    on_failure: always